import = ["/Users/dapats/.config/alacritty/catppuccin/kanagawa.toml"]

[cursor.style]
blinking = "Never"

[font]
size = 15.0

[font.normal]
family = "BerkeleyMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "BerkeleyMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "BerkeleyMono Nerd Font Mono"
style = "Italic"


[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 2
y = 5

# [key_bindings]
# { key: X, mods: Control|Shift, action: ToggleViMode }

[[keyboard.bindings]]
action = "ToggleViMode"
key = "X"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control|Shift"

[env]
TERM = "xterm-256color"

