add_newline = false

# format = """
# [→](bold green) $directory$git_branch$git_status
# """
#
format = """
$character $directory$git_branch$git_status
"""

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[➜](bold red) '

[git_branch]
symbol = " "
style = "bold red"
format = "[$symbol$branch(:$remote_branch)]($style) "
truncation_length = 8
truncation_symbol = ""

[git_status]
style = "bold blue"
format = '([\[$all_status$ahead_behind\]]($style) )'
